colopl/laravel-spanner

- README.md
- phpstan.neon
- src/Colopl/Spanner/Concerns/ManagesSessionPool.php
- src/Colopl/Spanner/Concerns/ManagesStaleReads.php
- src/Colopl/Spanner/Concerns/ManagesTransactions.php
- src/Colopl/Spanner/Connection.php
- tests/Colopl/Spanner/SessionNotFoundTest.php
fixes https://github.com/colopl/laravel-spanner/issues/37
There are a few cases when a 'Session not found' error can
[happen](https://cloud.google.com/spanner/docs/sessions#handle_deleted_sessions):
- Scripts that idle too long - for example, a [Laravel queue worker](https://laravel.com/docs/9.x/queues#the-queue-work-command)
or anything that doesn't call Spanner frequently enough (more than once an hour).
- The session is more than 28 days old.
- Some random flukes on Google's side.
> feat: handle 'session not found' errors

- phpstan.neon
- src/Colopl/Spanner/Concerns/ManagesTransactions.php
- tests/Colopl/Spanner/TransactionTest.php
The feature was added to the framework in v8 (but never mentioned in the release note).
https://github.com/laravel/framework/pull/35373
> fix: transaction callbacks where not being called

- src/Schema/Blueprint.php
- src/Schema/Grammar.php
- src/Schema/IndexDefinition.php
- tests/Schema/BlueprintTest.php
- tests/Schema/BuilderTest.php
`Blueprint::interleave` -> `interleaveInParent`
`IndexDefinition::interleave` -> `interleaveIn`
> feat: use more descriptive naming for interleave

- CHANGELOG.md
- phpstan.neon
- src/Concerns/ManagesSessionPool.php
- src/Session/CacheSessionPool.php
- src/Session/DeleteOperation.php
- src/SpannerServiceProvider.php
- tests/ConnectionTest.php
- tests/SessionNotFoundTest.php
A better implementation of https://github.com/colopl/laravel-spanner/pull/46.
Has no beaking change so it can be applied to v4.
Implementation is a direct copy of https://github.com/googleapis/google-cloud-php/pull/5774.
The only exception are the lines added to `Connection`.
> fix: session clear was not working correctly on CLI sessions

- CHANGELOG.md
- src/Connection.php
I wasn't fully confident at the time, but I think it should be safe to assume it's working now.
> feature: change default sessionNotFoundErrorMode to CLEAR_SESSION_POOL

- CHANGELOG.md
- src/Query/Concerns/AppliesForceIndex.php
This package broke on laravel 9.52.0 since it introduced their own version of forceIndex, which has a different arg signature.
> fix: match forceIndex arg with base class (added in laravel 9.52)

- CHANGELOG.md
- phpstan-baseline.neon
- phpstan.neon
- src/Schema/Grammar.php
No change in behavior. Makes it easier to transition to laravel 10.
> fix: Expression should go through Grammar::getValue

- CHANGELOG.md
- README.md
- composer.json
- phpstan-baseline.neon
- phpstan.neon
- src/Connection.php
- src/Query/Grammar.php
- src/Schema/Blueprint.php
- src/Schema/Grammar.php
- tests/Schema/BuilderTest.php
Fixed
- `Connection::reconnectIfMissingConnection` was changed from `protected` to `public` to match laravel 10.
- [Query/Expression](https://laravel.com/docs/10.x/upgrade#database-expressions) changed from `(string)$expr`to `$expr->toValue($grammar)`.
- Applied [QueryException constructor change](https://laravel.com/docs/10.x/upgrade#query-exception-constructor) to `Schema/Grammar`.
> feature: update to laravel 10

- Dockerfile
The bug where spanner hangs seems to be fixed
> chore: use latest grpc (1.49 -> 1.54) for test

- README.md
- composer.json
Fix: #94 
P.S. Due to the nature of being hosted on Packagist, it is necessary to cancel the v5.0.0 release. Otherwise, it will be installed improperly in the event of future incompatibility with minor PHP upgrades.
> Fix incorrect and weak requirements

- CHANGELOG.md
- src/FileCacheAdapter.php
- src/SpannerServiceProvider.php
- tests/ConnectionTest.php
- tests/TestCase.php
Reverts part of #63
Default umask for alpine linux is `0022` which forces directories to be created with permissions `0755`.
Since `spanner:warmup` is usually called from the cli, the cache directory is usually created by the cli user.
When a www user tries to use spanner, it will attempt to create a file in the cache directory but will get a permission denied error since the created directory has the permission `0755` and not `0777`.
This fix will set the umask to `0000` before creating the directory so it can be created with permission `0777`.
Test is lacking but there is no way to test 2 different users writing to a file through phpunit.
> fix: FilesystemAdapter could not make 0777 directories

- .gitattributes
- CHANGELOG.md
Added `/.github/`, `compose.yaml`, & `phpstan.neon` as `export-ignore`.
These are just needed for developing.
> Update `export-ignore` entries in `.gitattributes`

- CHANGELOG.md
- src/Concerns/ManagesTransactions.php
- tests/ConnectionTest.php
NOTE: Needs to be backported to v4.7.x.
> fix: Transaction state was not being cleared if rolled back failed

- Dockerfile
gRPC is a very large extension and takes a long time to compile. Use parallel compilation to speed up the setup of local environment.
Composer also changed because it is faster to retrieve from a pre-built image.
~- [ ] CHANGELOG~
> DX: optimize build local container image

- Dockerfile
This problem has been resolved in Upstream and is no longer necessary. Also, when `pecl_mt_install` was merged in #116 , it already made no sense.
See also: https://github.com/grpc/grpc/issues/25250
~- [ ] CHANGELOG~
> chore: Dockerfile: remove unused CPPFLAGS

- CHANGELOG.md
- phpstan.neon
- src/Schema/Grammar.php
- tests/Schema/BlueprintTest.php
> feat: add support for DROP IF EXISTS clause

- CHANGELOG.md
- src/Connection.php
- tests/Query/BuilderTest.php
> feat: support Query\Builder::toRawSql()

- CHANGELOG.md
- phpstan.neon
- src/Concerns/ManagesStaleReads.php
- src/Connection.php
- src/Query/Builder.php
- tests/ConnectionTest.php
- tests/Query/BuilderTest.php
Must be implemented before implementing https://github.com/colopl/laravel-spanner/issues/113
> feat: add Connection methods selectWithOptions and cursorWithOptions

- CHANGELOG.md
- src/Connection.php
- tests/ConnectionTest.php
- tests/Query/BuilderTest.php
Spanner bindings can also include list values.
> fix: escape list for Query/Builder::toRawSql

- src/Connection.php
- tests/Concerns/ManagesDataDefinitionsTest.php
- tests/ConnectionTest.php
- tests/SessionNotFoundTest.php
- tests/TestCase.php
Currently, there are dangling sessions after the test runs, which results in unstable results for `spanner:sessions` command.
This fix will delete sessions on the server side, whenever a test creates a new session.
> [5.2] fix: sessions were not cleared in some test cases

- CHANGELOG.md
- src/Connection.php
- tests/SessionNotFoundTest.php
Previously, if session pool was not set, nothing was being handled, but that results in stale connection.
The connection should be reconnected so that the missing session can be discarded.
> [5.2] fix: queries should be retried when session pool is undefined

- CHANGELOG.md
- README.md
- src/Connection.php
This is no longer needed since we now know running maintain doesn't remove any stale sessions that are "inUse".
https://github.com/googleapis/google-cloud-php/issues/6284#issuecomment-1665394907
> [6.0] feat: remove MAINTAIN_SESSION_POOL from SessionNotFoundErrorMode

- CHANGELOG.md
- README.md
- src/Connection.php
- tests/SessionNotFoundTest.php
There is no need for the user to "switch modes" because I found out that retrying is the expected behavior by the [Spanner Team](https://github.com/googleapis/google-cloud-java/pull/4734).
> [6.0] feat: remove Session Not Found Error Mode

- README.md
update the requirements section to show that its required to have spanner in googleSQL mode
> Update readme to mention GoogleSQL only

- CHANGELOG.md
- composer.json
- src/Concerns/ManagesTransactions.php
Laravel v10.32.0 requires explicit staging/clearing of transactions https://github.com/laravel/framework/pull/48859
without this code afterCommit jobs are never sent 
Fix: #
> fix: explicitly stage transaction to correctly run afterCommit jobs

- CHANGELOG.md
- composer.json
- src/Concerns/ManagesTransactions.php
- src/Query/Processor.php
- src/Schema/Builder.php
- src/Schema/Grammar.php
- tests/Query/BuilderTest.php
- tests/Schema/BuilderTest.php
- tests/TestCase.php
https://github.com/laravel/framework/pull/49103
> fix: laravel 10.34.0 changed database internals

- CHANGELOG.md
- phpstan.neon
- src/SpannerServiceProvider.php
Coming from https://github.com/googleapis/google-cloud-php/issues/6703#issuecomment-1846328959
Auth does not lock the cache file, so it's possible for a race condition to occur.
Below is an example of how that may happen.
1. Process 1: Auth opens cache
2. Process 2: Session Pool opens cache
3. Process 2: Session Pool creates a session and saves (file is written)
4. Process 1: Auth writes to cache (file is overwritten and session created at 3. no longer exists in cache)
Must be backported to 6.0.
> fix: separate auth cache and session pool to prevent race condition

- src/Query/Grammar.php
- tests/Query/BuilderTest.php
While its true spanner doesnt support explicit locking, I think the compileLock method should not throw an exception. It may be better to log a warning perhaps, but since spanner has complex lock handling and consistency, just gracefully allowing the lock to generate no additional code seems acceptable.
When using spanner with other frameworks (Laravel Nova in this case), it is necessary to ignore this.
Also if you look at: 
https://github.com/laravel/framework/blob/7907bfb50165b3951403e2d9882b4f8e0ee26b9e/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php#L29
and:
https://github.com/laravel/framework/blob/7907bfb50165b3951403e2d9882b4f8e0ee26b9e/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php#L340
You will see both of those return empty strings - I think graceful …
> query grammer compileLock - ignore

- src/Schema/Grammar.php
- tests/Schema/BlueprintTest.php
Json column type should be supported in the Schema Grammar.
Also added `typeMediumText()` and `typeLongText()` methods, no reason to not just map them to the basic `typeText()`
> add json and medium/long text column type

- CHANGELOG.md
- src/Schema/Grammar.php
- tests/Schema/BlueprintTest.php
Just another column type and associated tests
> Add typeChar as well

- CHANGELOG.md
- src/Concerns/ManagesTransactions.php
- tests/SessionNotFoundTest.php
Fix: #165 
Several features and tests were broken due to the `google/cloud-spanner v1.68.0` release.
* An exception is thrown if rollback is performed without any query call in the transaction.
* Tests that depend on the query execution order called from the `cursor()` method fail.
* https://github.com/googleapis/google-cloud-php-spanner/releases/tag/v1.68.0
> fix: fixed an error when rolling back a transaction that did not execute begin

- CHANGELOG.md
- src/Concerns/ManagesDataDefinitions.php
- tests/Concerns/ManagesDataDefinitionsTest.php
Different approach to achieve the same result for https://github.com/colopl/laravel-spanner/pull/164.
> fix: Connection::runDdlBatch should allow empty

- CHANGELOG.md
- src/Concerns/ManagesDataDefinitions.php
- tests/Concerns/ManagesDataDefinitionsTest.php
A different approach to fixing https://github.com/colopl/laravel-spanner/pull/162.
> feat: Allow pretending for DDL statements

- CHANGELOG.md
- src/Schema/Grammar.php
- tests/Schema/BlueprintTest.php
There is no need to do it on the client side. Server will throw a more precise error anyway.
Before:
```
LogicException: Cloud Spanner require a primary key!
```
After: 
```
Google\Cloud\Core\Exception\BadRequestException: {
"message": "Error parsing Spanner DDL statement: create table `Temp_20240126_054222_000` (`id` string(36) not null)  : Syntax error on line 1, column 67: Expecting 'PRIMARY' but found 'EOF'",
"code": 3,
"status": "INVALID_ARGUMENT",
"details": [
{
"@type": "grpc-status-details-bin",
"data": "<Unknown Binary Data>"
}
]
}
```
> feat: do primary key check on server side

- CHANGELOG.md
- phpstan.neon
- src/Query/Builder.php
- src/Query/Grammar.php
- src/Query/IndexHint.php
- tests/Query/BuilderTest.php
An [error is thrown](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/123682157cbf8fa5cb13f0d7edb9b66070bb4a11/common/errors.cc#L2539-L2554) when the following condition is met.
- Spanner Emulator is used
- index is defined as `NULL_FILTERED`
- FORCE_INDEX statement hint is set on the query
This allows it to be bypassed by calling `Builder::disableEmulatorNullFilterIndexCheck()`.
> feat: allow spanner_emulator.disable_query_null_filtered_index_check to be set

- CHANGELOG.md
- src/Concerns/ManagesTransactions.php
- tests/ConnectionTest.php
- tests/TransactionTest.php
Warning: `Connection::transaction()`'s `$attempts` argument's default value was changed from 10 to -1 (which is a magic number for default value which is 11). 
Default is set to 11 because Spanner library sets default retries to 10 and we add 1 to that since laravel defines amount of attempts not amount of retries.
> feat: allow default transaction attempts to be changed

- tests/ConnectionTest.php
- tests/Eloquent/ModelTest.php
- tests/Query/BuilderTest.php
- tests/Query/DatetimeTest.php
- tests/Query/ParameterizerTest.php
- tests/Query/SpannerArrayTest.php
- tests/Query/UnnestTest.php
- tests/Queue/QueueEventTest.php
- tests/Schema/BuilderTestLast.php
- tests/SessionNotFoundTest.php
- tests/TransactionTest.php
- Use `assertSame` instead of `assertEquals` (strict comparison vs loose comparison)
- `$this` instead of `self::` (some methods only exist in $this, so might as well be consistent)
> chore: use better test methods

- src/Schema/Builder.php
Since the usual behaviour of spanner is UUID primary keys, and the id/increments columns now create UUID columns by default, the default morphs type should be UUID
> Make default morphs type UUID

- CHANGELOG.md
- src/Schema/Builder.php
- tests/Schema/BuilderTestLast.php
Small tweak to Schema Builder dropAll() - if no tables exists simply return immediately
> dropAll() return immediately if no tables found

- CHANGELOG.md
- phpstan.neon
- src/Connection.php
- src/Query/Builder.php
- src/Query/Concerns/UsesMutations.php
- src/Query/Grammar.php
- tests/Query/BuilderTest.php
> feature: INSERT OR UPDATE (upsert) support

- CHANGELOG.md
- README.md
- phpstan.neon
- src/Concerns/ManagesTagging.php
- src/Concerns/ManagesTransactions.php
- src/Connection.php
- tests/Concerns/ManagesTagsTest.php
Fix: #189 
Request tag from test confirmed in Query Insights
Transaction tag from test confirmed in Transaction Insights
> feat: Transaction and request tagging support

- CHANGELOG.md
- compose.yaml
- src/Query/Grammar.php
- tests/Query/BuilderTest.php
> feat: add support for INSERT OR IGNORE

- CHANGELOG.md
- README.md
- src/Query/Builder.php
- src/Query/Concerns/SetsRequestTimeouts.php
- tests/Query/BuilderTest.php
Sometimes needed for "data boosted" queries since some requests take a long time to process.
> feat: allow request timeout at query level

- CHANGELOG.md
- src/SpannerServiceProvider.php
- tests/SpannerServiceProviderTest.php
> fix: authCache needs namespace for each connection

- CHANGELOG.md
- src/Connection.php
- tests/ConnectionTest.php
> fix: Timestamp bound queries were not applied when in transaction

- src/Query/Builder.php
https://github.com/laravel/framework/pull/51566 broke the signature and will now throw an error.
Closes https://github.com/colopl/laravel-spanner/issues/219
> fix: updateOrInsert signature change in 11.10

- src/Concerns/ManagesMutations.php
- src/Events/MutatingData.php
- src/Query/Concerns/UsesMutations.php
> fix: incorrect phpdoc for Mutations

- src/SpannerServiceProvider.php
`useGapicBackoffs` no longer exists in SpannerClient.
> chore: remove unused option "useGapicBackoffs"

- src/Query/Processor.php
- src/Schema/Builder.php
- src/Schema/Grammar.php
- tests/Schema/BuilderTestLast.php
Was only returning the index name (also with wrong key name).
It should be returning more data.
This fix will align it with other database drivers.
Also, dropAllTables was probably not working correctly, so that was fixed as well.
> fix!: SchemaBuilder::getIndexes was returning incorrect values

- README.md
- compose.yaml
- src/Schema/Blueprint.php
- src/Schema/Builder.php
- src/Schema/ColumnDefinition.php
- src/Schema/Grammar.php
- src/Schema/IntColumnDefinition.php
- tests/Schema/BlueprintTest.php
- tests/Schema/BuilderTestLast.php
- tests/TestCase.php
#273 and #275 needs to be fixed for analyze to pass.
> feat: allow auto increment to be set through Blueprint

- src/Concerns/ManagesDataDefinitions.php
DDL's take a long time to complete on normal Spanner so it makes sense to wait a second before completion.
This does not make sense when using the emulator because the emulator responds to the DDL almost instantly.
> feat: don't wait a whole second for DDL polling when using emulator
