colopl/laravel-spanner

.travis.yml, composer.json, phpunit.xml, tests/bootstrap.php
- `DB_SPANNER_INSTANCE_ID`
- `DB_SPANNER_PROJECT_ID`
- `GOOGLE_CREDENTIALS_ENCODED` (base64 encoded credential JSON to access Cloud Spanner)
=> Add Travis CI integration

README.md, src/Colopl/Spanner/Query/Concerns/UsesPartitionedDml.php
https://cloud.google.com/spanner/docs/dml-partitioned#features_that_arent_supported
>Cloud Spanner does not support some features for Partitioned DML:
>    INSERT is not supported.
=> Remove partitionedInsert()

README.md, src/Colopl/Spanner/Concerns/ManagesStaleReads.php, src/Colopl/Spanner/Connection.php, src/Colopl/Spanner/Query/Builder.php, src/Colopl/Spanner/Query/Concerns/UsesStaleReads.php, src/Colopl/Spanner/TimestampBound/ExactStaleness.php, src/Colopl/Spanner/TimestampBound/MaxStaleness.php, src/Colopl/Spanner/TimestampBound/MinReadTimestamp.php, src/Colopl/Spanner/TimestampBound/ReadTimestamp.php, src/Colopl/Spanner/TimestampBound/StrongRead.php, src/Colopl/Spanner/TimestampBound/TimestampBoundInterface.php, tests/Colopl/Spanner/ConnectionTest.php, tests/Colopl/Spanner/Query/BuilderTest.php, tests/Colopl/Spanner/TestCase.php
https://cloud.google.com/spanner/docs/timestamp-bounds
=> stale reads

src/Colopl/Spanner/Connection.php, tests/Colopl/Spanner/ConnectionTest.php
```
TransactionBeginning
TransactionCommitted
QueryExecuted
```
```
TransactionBeginning
QueryExecuted
TransactionCommitted
```
=> Fix connection event order on single-use DML

src/Colopl/Spanner/Schema/Blueprint.php
Foreign keys are supported now by Google Spanner
=> Add support of foreign keys in Blueprint

README.md
it seems typo, partitionedDelete() doesn't have any params
https://github.com/colopl/laravel-spanner/blob/ab3a6e13182037d8316ebf3ddefefde8bd82cf4e/src/Colopl/Spanner/Query/Concerns/UsesPartitionedDml.php#L45
```
public function partitionedDelete()
{
```
=> fix: incorrect spec of partitionedDelete()

CHANGELOG.md, phpstan.neon, src/CacheSessionPool.php, src/Colopl/Spanner/CacheSessionPool.php, src/Concerns/ManagesSessionPool.php, src/SessionInfo.php, src/SpannerServiceProvider.php, tests/ConnectionTest.php, tests/SessionNotFoundTest.php
Addresses https://github.com/googleapis/google-cloud-php/issues/5567.
Unfortunately, Google is unresponsive so we have to take care of it on our end.
=> fix: session clear was not working correctly on CLI sessions

src/Console/SessionsCommand.php, src/SpannerServiceProvider.php, tests/Console/SessionsCommandTest.php
This command does not work when used with emulator
=> Feature/add spanner:sessions command

src/Console/WarmupCommand.php, tests/Console/WarmupCommandTest.php
It will allow warmup to create fresh sessions instead of reusing existing ones.
=> feature: add refresh option for warmup

README.md, phpstan.neon, src/Schema/Blueprint.php, src/Schema/Grammar.php, src/Schema/IndexDefinition.php, src/Schema/InterleaveDefinition.php, tests/Schema/BlueprintTest.php, tests/Schema/BuilderTest.php
For autocompletion in PhpStorm
=> Feat: add action classes for interleave and index

CHANGELOG.md, src/Concerns/ManagesTransactions.php, tests/ConnectionTest.php
See test for when this might occur.
=> fix: Transaction was not cleared on NotFoundException

CHANGELOG.md, src/Query/Processor.php, src/Schema/Builder.php, src/Schema/Grammar.php, tests/Schema/BuilderTest.php
was list of string but should be row with name and type (differs for various databases)
=> Breaking Change: Schema\Builder::getAllTables was returning wrong type

.github/pull_request_template.md
This PR add pull request template to prevent CHANGELOG from leaking changes.
=> chore: add pull request template.

CHANGELOG.md, src/Schema/Grammar.php, tests/Schema/BlueprintTest.php
=> feature: add Schema\Grammar::typeDouble for better compatibility

CHANGELOG.md, src/Concerns/ManagesStaleReads.php, src/Connection.php, src/Schema/Builder.php
PHP 7+ allows for direct calling
=> feat: stop using call_user_func

CHANGELOG.md, README.md, phpstan.neon, src/Concerns/ManagesSessionPool.php, src/Concerns/ManagesStaleReads.php, src/Connection.php, src/Query/Builder.php, src/Query/Concerns/UsesDataBoost.php, tests/Query/BuilderTest.php
=> [6.0] feat: implement data boost

CHANGELOG.md, phpstan.neon, src/Console/SessionsCommand.php, src/Session/SessionInfo.php, tests/Console/SessionsCommandTest.php
=> feat: add label to spanner:list command

CHANGELOG.md, src/SpannerServiceProvider.php, tests/SpannerServiceProviderTest.php
=> feat: allow custom cache path

CHANGELOG.md, src/Query/Processor.php, src/Schema/Blueprint.php, src/Schema/Grammar.php, tests/Query/BuilderTest.php, tests/Schema/BlueprintTest.php, tests/TestCase.php, tests/test.ddl
=> feat: add NUMERIC column type support

CHANGELOG.md, src/Schema/Grammar.php, tests/Schema/BlueprintTest.php
Make dropForeign work, added tests and changelog info
=> add dropForeign compilation

CHANGELOG.md, src/Connection.php, src/Query/Processor.php, tests/Query/BuilderTest.php, tests/Query/SpannerArrayTest.php, tests/TestCase.php
Columns with array types that utilized specialized types like Numeric and Timestamp where not supported.
This PR adds support for them.
=> feat: support inserting and selecting DateTime/Numeric objects

tests/Schema/BlueprintTest.php, tests/TestCase.php
For better readability and consistency.
=> chore: clean up tests

.gitignore, Dockerfile, composer.json, phpunit.xml
=> chore: allow code coverage

src/Connection.php
=> If pretending, make affectingStatement runQueryCall without transaction

src/Connection.php
Will be removed in next major version (v9).
=> feat: deprecate Connection::getDoctrineConnection()

composer.json, src/Schema/Blueprint.php
broken by https://github.com/laravel/framework/pull/56324
=> fix: Blueprint::indexCommand signature broke in v12.21.0
